--- 
$schemaver: 1.1
name: skilltest
type: Web Service
aliases:
short_description: Github & AWS S3 API Skill Test
assignment_group: gro:AD-Student Life Applications
notes: 
maintained_by:
  - ndpete
developed_by_byu: True
ddd:
  business_domain: 
  ubiquitous_language_url: 
  context_map_url: 
links:
  system_documentation_url: 
  source_repo_url: https://github.com/test-ndpete-org/skilltest
  swagger_urls:
    - my-swagger.com
microservice: True
technologies_used:
  - Python
stages:
  deprecated:
    urls:
      product_page: yes
      physical_url: click.byu.edu
      virtual_url: byu.edu
    hosting_location: Other
    aws_account: 
    relationships: 
      depends_on:
        db_read_write:
        db_read_only:
        software:
      supports:
        software:
        service:
      reverse_proxy: 
      runs_on:
        server_cluster:
        virtual_server:
        rack_server:
        blade_server:
tags:
  data-sensitivity: highly confidential
  env: deprecated
  app: skilltest
  team: aws-id-admin
federation_json_url: https://raw.githubusercontent.com/test-ndpete-org/skilltest/master/.repo-meta.yml
x-anything: