---
$schemaver: 2.0
source_repo_url: https://github.com/test-ndpete-org/skilltest
deployables:
  - name: skilltest
    type: Library
    aliases:
    short_description: Github & AWS S3 API Skill Test
    assignment_group: gro:oit-app dev  student life apps
    notes:
    maintained_by:
      - ndpete
      - brettbeatty
    developed_by_byu: true
    ddd:
        business_domain:
        ubiquitous_language_url:
        context_map_url:
    links:
        system_documentation_url: https://github.com/test-ndpete-org/skilltest
        swagger_urls:
    microservice: true
    technologies_used:
      - Python
    stages:
        development:
            urls:
                product_page:
                physical_url:
                virtual_url:
            hosting_location:
            aws_account:
            relationships:
                depends_on:
                    db_read_write:
                    db_read_only:
                    software:
                supports:
                    software:
                    service:
                reverse_proxy:
                runs_on:
                    server_cluster:
                    virtual_server:
                    rack_server:
                    blade_server:
    tags:
        data-sensitivity: confidential
        env: dev
        team: gro:oit-app dev  student life apps
        app: skilltest
